---
- hosts: 172.31.2.90
  become: yes
  tasks:
  -  include_tasks: myfile.yml
  -  name: i want to create directory
     file:
       path: /home/lakki/myfolder
       state: directory
  - name: i want to copy test file
    copy: 
      src: mytextfile
      destination: /home/lakki/myfolder/mytextfile  
