---
- hosts: 172.31.1.153
  become: yes
  tasks:
  -  include_tasks: myfile.yml
  -  name: i want to create directory
     file:
       path: /home/lakki/myfolder
       state: directory
  -  name: i want to copy test file
     copy: 
      src: mytextfile
      dest: /home/lakki/myfolder/mytextfile  

  -  name: install apache2
     apt: 
       name: apache2
       state: present    

  -  name: i want to copy index file into nodes
     template:
          src: myindex.j2
          dest: /var/www/html/index.html 
     notify: restart web server        

  -  name: i want to download internet(remote) file
     get_url:
         url: https://github.com/Lpurushotham/myansiblepractice/blob/main/mywebserver.yml
         dest: /home/lakki/myfolder/installjava.yml
         force_basic_auth: yes

  handlers:
  -  name: restart web server
     service:
        name: apache2
        state: restarted
