---
- hosts: 172.31.1.153
  become: yes
  tasks:
  -  include_tasks: myfile.yml
  -  name: i want to create directory
     file:
       path: /home/lakki/myfolder
       state: directory
  -  name: i want to copy test file
     copy: 
      src: mytextfile
      dest: /home/lakki/myfolder/mytextfile  

  -  name: install apache2
     apt: 
       name: apache2
       state: present    

  -  name: i want to copy index file into nodes
     template:
          src: myindex.j2
          dest: /var/www/html/index.html     

  -  name: i want to download internet(remote) file
     get_url:
         get_url: https://github.com/Lpurushotham/myansiblepractice1/blob/main/installjava.yml
         dest: /home/lakki/myfolder/installjava.yml
         force_basic_auth: yes