---
- hosts: 172.31.1.153
  become: yes
  tasks: 
  - name: install git (apt-get install git)
    apt:
      name: git
      state: present
    tags: mygit  

  - name: install tree (apt-get install tree)
    apt:
      name: tree
      state: present
    tags: mytree

  - name: install wget (apt-get install wget)
    apt:
      name: wget
      state: present
    tags: mywget